# -*- coding: utf-8 -*-
"""Раскладка кадров: Dirty Margins, «DoorDash Isn't the One Taking Your Money».

Каждый кадр: S(a, b, room, what, txt)
  a, b  — строки сценария (script_delivery.txt, с 1), которые идут под этим кадром;
  room  — ключ из ROOMS;
  what  — что в кадре (англ.); персонажи называются тегами:
          "the raccoon", "the customer in the grey coat", "the driver in the red hoodie",
          "the burger cook", "the pizza owner", "the writer with glasses";
  txt   — надпись на предмете (≤ 4 слов или одно число); пусто — кадр без текста.
C(a, b, label) — схема с цифрами, собирается в монтаже, во Flow не генерируется.

Бренды в кадр не пишем (NOTEXT запрещает логотипы): приложение — это енот и
безымянный телефон, Grubhub/7-Eleven/McDonald's — безымянные места.
"""

SHOTS = []


def S(a, b, room, what, txt=""):
    SHOTS.append(dict(a=a, b=b, room=room, what=what, txt=txt, mode="bake" if txt else ""))


def C(a, b, label):
    SHOTS.append(dict(a=a, b=b, room="", what=label, txt="", mode="chart"))


# ---------------------------------------------------------------- ХУК 1–38
S(1, 1, "burger", "A big double cheeseburger meal on a red tray on the counter, seen close, a large price tag stuck in the bun.", "$15")
S(2, 2, "doorstep", "The same burger meal in a crumpled paper delivery bag on a doormat, seen close, a large paper receipt stapled to the bag.", "$38")
S(3, 3, "home", "The customer in the grey coat holds the paper receipt at arm's length and frowns at it.")
S(4, 4, "street", "Wide view of a rainy night street, heavy rain, puddles glowing under streetlights, one lit apartment window.")
S(4, 4, "home", "The customer in the grey coat on the sofa under a blanket, the dark window behind streaked with rain, an empty cold stove visible in the kitchen corner.")
S(5, 5, "phone", "A thumb tapping a big smartphone, the screen a grid of colourful food pictures, seen close.")
S(6, 6, "burger", "Wide view of a friendly small burger restaurant, warm light, the cook flipping patties behind the counter.")
S(6, 6, "burger", "A large chalkboard menu by the register, seen close, a chalk drawing of a burger meal and one big chalk price.", "$15")
S(7, 7, "phone", "A big smartphone screen showing the same burger meal picture with a large price under it, seen close.", "$17.50")
S(8, 8, "home", "The customer in the grey coat glances at the rainy window and pulls the blanket higher.")
S(9, 9, "phone", "A finger pressing a big round plus button next to a burger picture on a phone screen, seen close, a tiny shopping cart icon bouncing.")
S(10, 10, "phone", "A thumb about to press one huge button at the bottom of a phone screen, seen close.", "CHECKOUT")
S(11, 11, "phone", "The raccoon standing next to a giant smartphone as tall as he is, holding a long paper receipt that curls down to the floor.")
S(12, 12, "phone", "A giant phone screen with one new line sliding in, the raccoon pushing it in with both paws.", "DELIVERY FEE")
S(13, 13, "phone", "A giant phone screen, the raccoon sticking a second paper strip onto it.", "SERVICE FEE")
S(14, 14, "phone", "The raccoon holding up a tiny burger between two fingers with a mocking look, a small paper tag hanging from it.", "SMALL ORDER")
S(15, 15, "phone", "A giant phone screen with one more short line, a small stamp in the raccoon's paw pressing it on.", "TAX")
S(16, 16, "phone", "A phone screen with three big round tip buttons, the middle one already glowing bright orange, seen close.", "20%")
S(17, 17, "phone", "A phone screen total with a big bold number, the burger picture shrinking beside it, seen close.", "$38")
S(18, 19, "home", "The customer in the grey coat holding the phone in one hand and a plain paper menu picture in the other, comparing them, puzzled.")
S(20, 20, "phone", "A thumb pressing a big green pay button on the phone, rain drops on the window behind.")
S(21, 21, "home", "The customer in the grey coat pacing by the window, checking the phone, a tiny delivery car icon crawling on its map.")
S(22, 22, "home", "The customer in the grey coat scowling at the phone, steam puffing from his ears, cartoon style.")
S(23, 23, "office", "The raccoon in a big leather chair behind a desk, a tall stack of green cash beside him, grinning.")
S(24, 24, "office", "The raccoon turns the stack of cash over: it is only a thin layer of bills on top of an empty cardboard box.")
S(25, 25, "street", "Wide view from above of a city at night, hundreds of tiny delivery cars with glowing bags on their roofs.")
C(26, 26, "$102 BILLION — потрачено через приложение за год")
S(27, 27, "office", "The raccoon behind the desk pushing one single coin across the table with one finger.")
S(28, 28, "office", "One small copper coin on the desk, seen close, a big paper tag leaning on it.", "29¢")
S(29, 29, "office", "The raccoon holding a much smaller coin with tweezers, squinting at it.", "5¢")
S(30, 30, "office", "The raccoon with his empty pockets turned out, an empty coin jar on the desk.")
S(31, 31, "home", "The customer in the grey coat scratching his head, holding the phone.")
S(32, 32, "burger", "The burger cook behind the counter pointing angrily at a phone lying on the counter.")
S(33, 33, "car", "The driver in the red hoodie in the car, pointing one thumb at the phone and the other back at the restaurant window.")
S(34, 34, "office", "The raccoon shrugging with both paws up, a thin wallet hanging open from his apron pocket.")
S(35, 35, "street", "The burger cook, the driver in the red hoodie and the raccoon standing in a row under one umbrella in the rain, each pointing at a different one.")
S(36, 37, "office", "The raccoon handing a long paper receipt straight toward the viewer, the paper blank.")
S(38, 38, "office", "The raccoon holding a finger to his lips, winking, a paper receipt folded in his other paw.")

# ---------------------------------------------------------------- РАНЬШЕ 39–61
S(39, 39, "pizza_old", "Wide view of an old-fashioned pizza place from twenty years ago, a boxy old TV on the wall, a rotary phone on the counter.")
S(40, 40, "pizza_old", "A rotary phone on the counter ringing, the receiver jumping, seen close.")
S(41, 41, "pizza_old", "A pizza box and a white paper takeout box with chopsticks side by side on the counter.")
S(42, 42, "pizza_old", "The pizza owner writing an order on a paper pad by the phone.")
S(43, 43, "pizza_old", "Two young drivers in matching red caps sitting on a bench in the back room, pizza boxes stacked beside them.")
S(44, 44, "street", "An old small hatchback car at night with a glowing sign on its roof shaped like a slice of pizza.")
S(45, 45, "pizza_old", "A paper street map pinned on the wall with a big circle drawn around the restaurant, a pin in the middle.")
S(46, 46, "pizza_old", "The pizza owner handing a warm pizza box to one of his drivers in a red cap.")
S(47, 47, "street", "A pizza box on the passenger seat of the old hatchback, steam still rising, a small kitchen timer on top.")
S(48, 48, "street", "Three restaurants side by side at night, a burger place, a taco place and a sushi bar, all with closed doors, no cars outside.")
S(49, 49, "office", "The raccoon in a smart green apron over a white shirt, standing at a restaurant door holding a shiny tablet, smiling like a salesman.")
S(50, 50, "burger", "The raccoon pointing at the empty spot where a delivery car would park.")
S(51, 51, "burger", "The raccoon closing the burger cook's old laptop with one paw.")
S(52, 52, "burger", "The raccoon unrolling a big colourful poster with a phone, a car and a credit card drawn on it.")
S(53, 53, "burger", "The burger cook happily flipping patties while the raccoon pats his shoulder.")
S(54, 54, "street", "Wide view of a whole town street at night, every restaurant window glowing, a stream of delivery bags leaving every door.")
S(55, 55, "burger", "The raccoon sweeping a pile of coins under the rug with a broom.")
S(56, 56, "car", "The driver in the red hoodie holding out an open paw for money.")
S(57, 57, "gas", "A car at a gas pump at night, the pump numbers spinning.")
S(58, 58, "support", "A support worker with a headset at a desk, answering a ringing phone, looking tired.")
S(59, 59, "phone", "The raccoon carrying a heavy sack out of a kitchen door and emptying it into a giant phone screen.")
S(60, 60, "burger", "An empty dining room with chairs up on the tables, a paper sign on the door, rain outside.", "CLOSED")
S(60, 60, "burger", "The burger cook plugging a thick cable from a tablet into the wall, reluctant, while the raccoon holds the plug.")
S(61, 61, "street", "Wide view of a rainy street with delivery drivers on bikes and in cars, bags glowing, restaurants lit up.")

# ---------------------------------------------------------------- ПИЦЦА 62–91
S(62, 62, "pizza", "A whole pizza on a wooden board on the counter, seen close.")
S(63, 63, "writer", "The writer with glasses at a desk with a laptop, his phone ringing, a mug of coffee beside him.")
S(64, 64, "pizza", "Wide view of a small cosy pizza place, the pizza owner behind the counter talking on the phone.")
S(65, 65, "pizza", "A few small tables, a regular customer waving to the pizza owner as he leaves with a box.")
S(66, 66, "pizza", "The pizza owner staring at a phone screen that shows a picture of his own restaurant, shocked.")
S(67, 68, "pizza", "The pizza owner holding up an empty contract paper with no signature, puzzled.")
S(69, 69, "office", "The raccoon copying a paper menu into a giant phone with a pen, humming, alone in the office at night.")
S(70, 70, "office", "The raccoon's pen slipping, a big ink blot on the menu.")
S(71, 71, "pizza", "A deluxe pizza piled high with toppings on the counter, a big price tag in it, seen close.", "$24")
S(72, 72, "phone", "The same deluxe pizza on a phone screen with a big price under it, seen close.", "$16")
S(73, 73, "writer", "The writer with glasses leaning close to his laptop, eyebrows raised.")
S(74, 74, "pizza", "The driver in the red hoodie at the pizza counter, paying the pizza owner with a card.")
S(75, 75, "phone", "A phone screen showing a big price paid by the customer, seen close.", "$16")
S(76, 76, "pizza", "The pizza owner's register drawer open, a big paper slip on top of the cash.", "$24")
C(77, 77, "−$8 на каждой пицце")
S(78, 78, "writer", "The writer with glasses and the pizza owner leaning over the laptop together, grinning.")
S(79, 79, "phone", "A phone screen with a big number next to a pizza picture, a finger pressing plus again and again, seen close.", "x10")
S(80, 81, "pizza", "The pizza owner making ten pizzas at once, boxes stacked to the ceiling.")
S(82, 82, "doorstep", "Ten pizza boxes stacked on a friend's porch under a porch light, rain around.")
S(83, 83, "phone", "A phone screen with a big total, seen close.", "$160")
S(84, 84, "pizza", "The driver in the red hoodie handing a thick stack of cash to the pizza owner at the counter.", "$240")
S(85, 85, "pizza", "One pizza box with a small price tag on the lid, seen close.", "$7")
C(86, 86, "$240 − $160 − 10×$7 = +$10 владельцу")
S(87, 87, "pizza", "The pizza owner sliding plain bare pizza dough with no toppings into a box, laughing.")
S(88, 88, "pizza", "The writer with glasses and the pizza owner laughing, high-fiving over the counter.")
S(89, 89, "office", "The raccoon looking at the pizza story on his phone, not laughing, calm and knowing.")
S(90, 90, "office", "The raccoon stacking three things on his desk: a small restaurant model, a phone, and a padlock over a rival's toy car.")
S(91, 91, "office", "The raccoon tapping his temple with a sly look.")

# ---------------------------------------------------------------- ЧЕК 92–145
S(92, 92, "office", "The raccoon threading a long empty paper receipt into an old cash register.")
S(93, 94, "office", "A long paper receipt pinned to a corkboard, seen close, only one line at the very top.", "$38")
S(95, 95, "office", "The raccoon holding a pen over the long receipt, ready to write.")
S(96, 96, "office", "The raccoon holding a burger in one paw and a scale in the other.")
S(97, 97, "office", "The raccoon opening a very thick bound annual report on his desk.")
C(98, 98, "$102 BILLION — всё, что заплатили клиенты за 2025 год")
S(99, 99, "office", "A wide wooden table with a burger, a stack of fee slips, a tip jar and a tax stamp laid out in a row.")
S(100, 100, "street", "Wide view from above of a huge sea of paper delivery bags stretching to the horizon.")
C(101, 103, "$102B ÷ 3.2B заказов = $32.16")
S(104, 104, "office", "The raccoon pulling one crisp bill toward himself across the desk.")
S(105, 105, "office", "The thick annual report open on the desk, seen close, one page marked with a red bookmark.")
S(106, 106, "office", "A one-dollar bill cut with scissors, a thin slice falling off, seen close.", "13.5¢")
S(107, 108, "office", "A small neat pile of coins and bills on the desk, seen close, a tag leaning on it.", "$4.32")
S(109, 109, "office", "The raccoon sitting in front of his small pile of money, arms crossed.")
C(110, 110, "$32.16 − $4.32 = $27.84 уходит другим")
S(111, 111, "burger", "Money flowing in through the burger restaurant door as the burger cook catches it in his apron.")
S(112, 112, "car", "The driver in the red hoodie tucking bills into the car's sun visor.")
S(113, 113, "cityhall", "A tax clerk behind a wooden counter stamping a paper, coins sliding into a big jar.")
S(114, 115, "office", "The raccoon guarding his small pile of money with both paws, looking around.")
S(116, 116, "office", "A big hungry cartoon paper shredder on the desk, eating bills from the raccoon's pile.")
S(117, 118, "office", "The raccoon yawning, then snapping awake as the shredder grabs his sleeve.")
S(119, 119, "office", "A credit card sliding through a card reader, seen close, a coin jumping out.")
S(120, 120, "car", "The driver in the red hoodie driving with a hot bag on the passenger seat, a big insurance paper tucked under the seat belt.")
S(121, 121, "support", "A support worker with a headset listening, an empty fries carton on her desk.")
S(122, 122, "office", "The raccoon handing money back through a small window, frowning.")
S(123, 123, "home", "The customer in the grey coat receiving coins back on his phone, a cold burger on the table.")
S(124, 124, "burger", "A finished burger meal left on the pickup shelf, nobody coming for it, the burger cook sighing.")
S(125, 125, "office", "Half of the raccoon's small pile of money gone, a tag on the rest, seen close.", "$2.12")
S(126, 126, "office", "The raccoon on a stage with a megaphone.")
S(127, 127, "office", "The raccoon holding a single coin next to a billboard with a giant phone picture, seen close.", "78¢")
S(128, 128, "home", "A TV showing a football game, a delivery ad bubble popping onto the screen, the customer in the grey coat watching.")
S(129, 130, "pizza", "The raccoon secretly paying extra money for a pizza at the pizza counter, with a wink.")
S(131, 131, "office", "Three engineers at computers with lines of colourful code, the raccoon handing each a coin.", "45¢")
S(132, 132, "office", "A glass meeting room with lawyers in suits, a coin on the table.", "50¢")
S(133, 133, "server", "A room full of tall humming server racks, one rack smoking a little, seen wide.", "24¢")
S(134, 134, "office", "The raccoon turning his little money bag upside down, almost nothing falls out.")
C(135, 135, "$935 MILLION прибыль DoorDash за 2025")
C(136, 137, "$935M ÷ 3.2B = 29¢")
S(138, 138, "office", "The long receipt on the corkboard with a new first line, the raccoon writing it, seen close.", "APP: 29¢")
S(139, 139, "office", "The raccoon holding a tiny trophy, looking unimpressed.")
S(140, 140, "office", "The raccoon holding a very small coin on his fingertip.", "5¢")
S(141, 141, "office", "The raccoon sitting in a puddle on the floor, a big hole in his money bag, rain leaking through the ceiling.", "-$0.5B")
S(142, 142, "office", "A cartoon villain's chair turned around, and in it is the raccoon counting only three coins.")
S(143, 143, "office", "The raccoon on a slowly rising line drawn on a whiteboard, still below the zero line.")
S(144, 145, "burger", "The raccoon peeking through the round window of the restaurant kitchen door.")

# ---------------------------------------------------------------- РЕСТОРАН 146–191
S(146, 147, "kitchen", "The burger cook in the kitchen, sweating over a hot grill full of patties, fryer bubbling.")
S(148, 148, "kitchen", "The burger cook paying a pile of bills from a small cash box: a food supplier, a landlord and a waiter each holding out a hand.")
S(149, 149, "office_nra", "A thick survey report on a desk, pages full of little charts, a pencil on top.")
C(150, 150, "2.8% прибыль ресторана с официантами")
C(151, 151, "4% прибыль фастфуда")
S(152, 153, "kitchen", "A few coins in the burger cook's palm next to a whole burger, seen close.", "42¢")
S(154, 154, "kitchen", "The burger cook sitting on a crate by the back door, holding the few coins, tired.")
S(155, 156, "burger", "The raccoon laying three shiny cards on the counter in front of the burger cook, like a salesman.")
S(157, 157, "burger", "The first card on the counter, seen close.", "15%")
S(158, 158, "burger", "The second card on the counter, seen close.", "25%")
S(159, 159, "burger", "The third card, gold, on the counter, a small spotlight on it, seen close.", "30%")
C(160, 162, "ресторан 3%  vs  приложение 15–30%")
S(163, 163, "burger", "The raccoon taking a big bite out of the burger on the counter, leaving the cook a small crumb.", "$4.50")
S(164, 165, "burger", "The burger cook climbing a ladder to rewrite the chalkboard menu.")
S(166, 167, "burger", "The chalkboard menu next to a phone leaning on the register, both showing the same burger.")
S(168, 169, "kitchen", "The burger cook doing sums on a paper bag with a pencil, shaking his head.")
C(170, 170, "в приложении дороже на 10–20%, в среднем ~15%")
S(171, 171, "burger", "A price tag on a burger stretched upward like rubber by the raccoon's paw.")
C(172, 172, "+71% в приложении против кассы (пример с фастфудом)")
S(173, 173, "office", "The long receipt on the corkboard, a second line written in invisible ink that only glows under a lamp the raccoon holds.")
S(174, 174, "office", "The glowing second line on the receipt, seen close.", "MARKUP")
S(175, 175, "burger", "The customer in the grey coat unknowingly handing an extra coin to the burger cook, who passes it straight on to the raccoon.")
S(176, 177, "kitchen", "The burger cook glaring at a tablet on the wall that keeps printing orders.")
S(178, 178, "kitchen", "The burger cook packing a delivery bag with a heavy sigh.")
S(179, 179, "street", "Two burger restaurants side by side at night, one dark, one busy with a line of delivery drivers.")
S(180, 180, "mall", "Wide view of a shopping mall hallway, one shop right by the entrance with a big crowd, the raccoon as landlord holding its key.")
S(181, 182, "mall", "An empty shop at the far quiet end of the mall hallway, nobody walking past.")
S(183, 183, "burger", "The burger cook raising the price on the chalkboard while the customer in the grey coat pays more, the raccoon collecting.")
S(184, 184, "kitchen", "The burger cook counting only a few coins at the end of the night, the kitchen dark.")
S(185, 185, "office", "The raccoon reading the long receipt on the corkboard with a magnifying glass.")
S(186, 186, "office", "The receipt's first line, seen close.", "APP: 29¢")
S(187, 187, "office", "The receipt's second line, seen close.", "MARKUP ~$2.50")
S(188, 188, "kitchen", "A tiny coin on the burger cook's palm.", "~40¢")
S(189, 189, "office", "The raccoon and the burger cook side by side, both with empty pockets turned out.")
S(190, 191, "street", "The customer in the grey coat in a detective hat following wet footprints of money coins down the rainy street.")

# ---------------------------------------------------------------- КУРЬЕР 192–239
S(192, 193, "car", "The driver in the red hoodie behind the wheel, an insulated delivery backpack on the back seat.")
S(194, 194, "parking", "Wide view of a big empty parking lot at night, one car with its interior light on, the driver in the red hoodie inside looking at a phone.")
S(195, 195, "car", "A phone in a holder on the dashboard lighting up with a ping, seen close.")
S(196, 196, "car", "The phone screen showing a small map with two pins and a route line, seen close.")
S(197, 197, "car", "The phone screen with an offer, a big amount on it, seen close.", "$6.50")
S(198, 198, "car", "The driver in the red hoodie with a thumb above the phone, a small countdown ring shrinking on the screen.")
S(199, 200, "office", "The raccoon shaking his head and pointing away from his office.")
S(201, 201, "car", "The driver in the red hoodie holding a paper contract that says only one word.", "CONTRACTOR")
S(202, 202, "gas", "The driver in the red hoodie at a gas pump, paying for gas, an insurance bill and a phone bill sticking out of his pocket.")
S(203, 204, "car", "The six dollars fifty in the driver's hand, most of it going into the gas tank.")
S(205, 205, "street", "Wide view of a city street at night full of delivery drivers on bikes, scooters and in cars.")
C(206, 206, "8M+ курьеров в США · почти $20B заработка с чаевыми")
S(207, 207, "car", "The driver in the red hoodie looking up in surprise.")
C(208, 208, "в среднем ~4 часа в неделю, ~10 недель в году")
S(209, 210, "home_driver", "The driver in the red hoodie in a small apartment, a big red rent envelope on the table, grabbing the car keys.")
S(211, 211, "phone", "A phone tip screen with three round buttons, seen close.")
S(212, 212, "office", "The raccoon holding the annual report, pointing at one line.", "100% TIPS")
S(213, 213, "car", "The driver in the red hoodie pocketing a tip with a small smile.")
S(214, 214, "office", "The raccoon looking away and whistling.")
S(215, 215, "office", "A calendar on the office wall flipped back to an older year.", "2017")
S(216, 216, "car", "A paper pay slip in the driver's hand, seen close.", "$7")
S(217, 217, "office", "The customer in the grey coat dropping three coins into the driver's tip jar, while the raccoon takes the same number of coins back out of the driver's pay envelope.")
S(218, 218, "car", "The driver in the red hoodie holding the same seven dollars as before, unchanged.")
S(219, 220, "office", "The raccoon slipping the customer's tip coins into his own apron pocket with a sly grin.")
S(221, 221, "court", "A courtroom, the raccoon standing before a judge's bench holding a cheque, ears down.")
S(222, 222, "court", "A giant cheque on an easel in the courtroom, seen close.", "$16.75M")
S(223, 223, "phone", "A phone tip screen with the middle button glowing, a faint shadow of a raccoon paw behind it.", "20%")
S(224, 225, "cityhall", "A city council chamber, council members raising their hands to vote.")
S(226, 226, "cityhall", "A new rule paper nailed on a wooden board in the city hall, seen close.", "$22.13/HR")
S(227, 227, "car", "The driver in the red hoodie smiling, holding a slightly thicker envelope of pay.")
S(228, 228, "office", "The raccoon opening the thick annual report at a folded page.")
S(229, 229, "office", "The raccoon writing a new fee line on a big sheet with a fat marker.")
S(230, 231, "phone", "A phone checkout screen with one more fee line appearing, the customer in the grey coat's thumb hovering above.", "FEE")
S(232, 234, "office", "The long receipt on the corkboard, a third line written in, seen close.", "DRIVER")
S(235, 235, "gas", "The driver in the red hoodie watching the gas pump numbers roll up, his pay envelope getting thin.")
S(236, 236, "street", "The raccoon, the burger cook and the driver in the red hoodie sitting on the curb in the rain, each with a few coins.")
S(237, 237, "office", "The raccoon holding up one coin.", "29¢")
S(238, 238, "kitchen", "The burger cook holding up one coin.", "42¢")
S(239, 239, "gas", "The driver in the red hoodie holding an almost empty envelope next to a full gas tank gauge.")

# ---------------------------------------------------------------- ДИЗАЙН СБОРОВ 240–263
S(240, 241, "home", "The customer in the grey coat looking at a long receipt with a magnifying glass.")
S(242, 243, "office", "The raccoon drawing a blueprint of a price tag on a drafting table with a ruler and compass.")
S(244, 245, "office", "An old dusty trophy on a shelf, the second delivery company's old empty desk behind it.")
S(246, 246, "court", "Wide view of a courtroom, a big wooden bench, two government lawyers carrying fat folders in.")
S(247, 247, "court", "A government lawyer reading a long scroll aloud in court.")
S(248, 248, "phone", "A phone screen with a huge smiling offer banner, and small hidden fees piling up at the bottom of the screen.", "FREE")
S(249, 249, "office", "One big fee slip cut in half with scissors into two smaller slips.")
S(250, 250, "car", "A driver looking at a big promise poster of cash, then at a small coin in his hand.")
S(251, 251, "phone", "A phone screen with a restaurant picture, the pizza owner outside the screen shaking his head no.")
S(252, 253, "pizza", "The pizza owner in his shop raising an eyebrow, holding the same empty contract as before.")
S(254, 254, "court", "A giant cheque on an easel in the courtroom, seen close.", "$140M")
S(255, 255, "court", "A company lawyer turning out empty pockets, a smaller cheque on the table, seen close.", "$25M")
S(256, 256, "home", "The customer in the grey coat opening a paper envelope from a mailbox, a refund cheque inside.")
C(256, 256, "$24M возвратов клиентам (FTC)")
S(257, 258, "office", "The raccoon at a drafting table carefully designing the shape of a price tag, very focused.")
S(259, 259, "phone", "A phone screen showing one big total on the very first screen, the customer in the grey coat pulling back his thumb.", "$38")
S(260, 260, "phone", "A staircase of small price steps going up, the customer in the grey coat walking up it one step at a time without noticing.")
S(261, 263, "office", "The long receipt on the corkboard, a fourth line with a small drawing of a ruler and pencil, seen close.", "DESIGN")

# ---------------------------------------------------------------- ВИРТУАЛЬНЫЕ КУХНИ 264–292
S(264, 265, "ghost", "A plain kitchen back door in an alley, many different delivery bags coming out of the same door.")
S(266, 266, "studio", "A young YouTuber's studio with ring lights and cameras, a big burger on the desk, a crowd of fans cheering on a screen. The YouTuber is seen only from behind.")
S(267, 267, "burger_brand", "A shiny burger box with a big cartoon lightning bolt on the lid, seen close.")
C(268, 269, "~1700 точек за 2 года")
S(270, 270, "street", "A map of the world on a wall covered in hundreds of pins, seen wide.")
S(271, 271, "office", "The raccoon opening a curtain to reveal a secret.")
S(272, 272, "burger_brand", "One single bright real burger restaurant with a line of fans outside, seen wide.")
S(273, 273, "ghost", "A normal old diner kitchen, the cook of the diner making a burger that he puts into a shiny branded box.")
S(274, 274, "ghost", "A man in a suit handing a diner cook a recipe card, a stack of branded boxes and a sticker roll.")
S(275, 275, "ghost", "A cook at one stove making a diner meal in one pan and the branded burger in the next.")
S(276, 276, "street", "The driver in the red hoodie carrying the shiny branded burger box out of the old diner.")
S(277, 278, "phone", "A phone screen with one big shiny button with a burger picture, a finger pressing it.")
S(279, 279, "phone", "A phone screen filling up with angry red one-star ratings, seen close.")
S(280, 280, "court", "A courtroom, two lawyers facing each other across the aisle, each holding a thick lawsuit folder.")
S(281, 281, "home", "The customer in the grey coat grimacing at a soggy burger in a shiny box.")
S(282, 282, "street", "A parent in a raincoat with two kids following a delivery route on a phone map at night.")
S(283, 283, "store", "A small corner convenience store at night, a hot dog roller and a microwave behind the counter, a shiny burger box on the counter.")
S(284, 284, "court", "A giant cheque on an easel in the courtroom, seen close.", "$100M")
S(285, 286, "office", "The raccoon holding up a mask shaped like a restaurant front in front of a plain kitchen.")
S(287, 287, "phone", "A phone screen with just a name bar, a food photo and a button, nothing else, seen close.")
S(288, 288, "ghost", "One small kitchen with ten different branded bags hanging on hooks, one cook in the middle.")
S(289, 289, "ghost", "One stove with ten pans at once, one cook juggling them, a rent bill pinned above.")
S(290, 290, "office", "The long receipt on the corkboard, the markup line underlined twice.")
S(291, 292, "phone", "A phone screen with a big shiny logo sticker being peeled off, a plain kitchen showing underneath.")

# ---------------------------------------------------------------- ЦЕНОВАЯ ВОЙНА 293–333
S(293, 294, "home", "The customer in the grey coat holding the phone with a question mark bubble over his head.")
S(295, 296, "pizza", "The pizza owner laughing, the stack of ten pizza boxes behind him.")
S(297, 297, "street", "Delivery companies' vans throwing free coupons into the air on a street like confetti.", "FREE")
S(298, 298, "boardroom", "The raccoon and a rival mascot, a cartoon fox in an orange apron, pulling one burger from both ends like a tug of war.")
S(299, 299, "boardroom", "The rope of the tug of war snapping, the fox falling backward.")
S(300, 300, "boardroom", "The fox in the orange apron sitting alone on the floor among empty boxes, sad.")
S(301, 301, "boardroom", "Wide view of a boardroom, a man in a European-style suit shaking hands with the fox over a huge cheque.", "$7.3B")
S(302, 302, "boardroom", "The same boardroom three years later, a much smaller cheque on the table, seen close.", "$650M")
S(303, 303, "boardroom", "A heavy iron ball and chain attached to the fox's ankle.", "DEBT")
C(304, 305, "$7.3B → ~$150M реальной стоимости")
S(306, 307, "street", "Wide view of a desert road with one big delivery truck driving on alone, small broken carts left behind at the roadside.")
S(308, 308, "office", "The raccoon shaking his head at a sale tag.")
S(309, 309, "office", "The raccoon growing giant, standing over a city like a building.")
S(310, 310, "office", "The giant raccoon scooping restaurants, cars and people into his apron pocket.")
S(311, 311, "street", "A red double-decker bus and a London street at night, a delivery rider on a bicycle.")
S(312, 313, "office", "The raccoon pulling a golden membership card out of his apron.")
S(314, 314, "phone", "A shiny golden membership card, seen close, a small crown on it.", "PASS")
S(315, 315, "phone", "A phone screen where a delivery fee line gets crossed out, a small monthly price tag beside it.")
C(316, 316, "35M+ подписчиков")
S(317, 317, "home", "The customer in the grey coat smiling at his phone.")
S(318, 318, "office", "A pipe on the office wall steadily dripping coins into the raccoon's bucket.")
S(319, 319, "phone", "A second phone on the table covered in dust and cobwebs.")
S(320, 320, "phone", "The raccoon pasting an ad poster onto the inside of a giant phone screen.")
S(321, 321, "phone", "A phone search screen with pizza results, the first result highlighted by a spotlight, seen close.", "SPONSORED")
S(322, 322, "pizza", "The pizza owner paying the raccoon twice: once with his left hand, once with his right.")
S(323, 323, "office", "A big money machine in a warehouse, printing ad posters.")
C(324, 325, "+$0.5B рекламной выручки в доставке за год (Uber)")
S(326, 326, "pizza", "The pizza owner paying a coin for a spotlight to shine on his shop inside a giant phone.")
S(327, 327, "pizza", "The pizza owner quietly adding a coin to the price tag of a pizza.")
S(328, 329, "pizza", "A menu board in the pizza place with prices going up, seen close.")
S(330, 331, "office", "The raccoon drawing a simple plan on a whiteboard: one big phone in the middle with arrows pointing at it from everywhere.")
S(332, 332, "home", "The customer in the grey coat with a small coin purse, the raccoon ignoring it.")
S(333, 333, "home", "The raccoon happily watching the customer in the grey coat open the phone again, his thumb going to the same spot automatically.")

# ---------------------------------------------------------------- ГОРОДА 334–351
S(334, 334, "cityhall", "Wide view of a city hall with columns at night, rain, light in the windows.")
S(335, 335, "cityhall", "A mayor figure putting a big metal lid on a jar of coins.")
C(336, 336, "потолок NYC: 15% доставка + 5% остальное")
S(337, 338, "court", "The raccoon and the fox in the orange apron carrying lawsuit folders up the courthouse steps, over and over, calendars flying off.")
S(339, 339, "court", "Lawyers shaking hands across a table.")
S(340, 340, "cityhall", "The lid on the coin jar lifted up high.", "43%")
C(341, 342, "до 43% с заказа — почти половина")
S(343, 343, "street", "A sunny California street with palm trees and delivery drivers.")
S(344, 344, "cityhall", "A state capitol building, a paper bill with a gold seal on a desk.")
S(345, 345, "ballot", "A voting booth with a paper ballot, seen close.", "PROP 22")
S(346, 346, "ballot", "A huge pile of campaign money, TV ads and billboards stacked on each other.", "$200M")
S(347, 347, "ballot", "The raccoon adding his own big sack of money to the pile.", "$48M")
S(348, 348, "ballot", "A ballot box with a green checkmark.")
S(349, 349, "office", "The raccoon holding one tiny coin in one paw and a huge sack of money in the other.")
S(350, 351, "office", "The raccoon locking a small model of a whole delivery machine in a glass case.")

# ---------------------------------------------------------------- ЧЕСТНАЯ ЦЕНА 352–374
S(352, 353, "home", "The customer in the grey coat putting the phone face down on the table and taking out a notebook.")
S(354, 354, "home", "The customer in the grey coat with a pencil and a calculator, a burger drawing in the notebook.")
S(355, 355, "street", "The driver in the red hoodie at four stops of one delivery: accepting, driving, waiting at the counter, driving to a door, in one long picture.")
S(356, 357, "car", "A clock showing half an hour on the car dashboard, the driver holding bills.", "$11")
S(358, 358, "street", "The driver's car on a wet road at night.")
S(359, 359, "cityhall", "A tax office clerk with an official ruler measuring a road on a map.", "70¢/MILE")
S(360, 360, "gas", "The car at a gas pump, a tire leaning on it, an old worn wheel next to it.")
S(361, 361, "street", "A small car driving a looping route between a restaurant and a house, seven small mile markers along the road.", "$5")
C(362, 363, "$11 человек + $5 машина ≈ $16 на один бургер")
S(364, 364, "office", "The long receipt on the corkboard, the customer in the grey coat looking at it.")
C(365, 366, "сборы ~$8–10 + чаевые")
S(367, 369, "home", "The customer in the grey coat nodding slowly at the receipt.")
S(370, 370, "office", "The raccoon sitting down on a chair, holding his head.")
S(371, 371, "phone", "A phone lying on the table with nothing happening, just a phone.")
S(372, 372, "street", "A small car driving in the rain at night, seen wide, one delivery bag on its roof.")
S(373, 373, "street", "Wide view of the whole city at night, one small car crossing it for one burger.")
S(374, 374, "office", "A computer screen full of colourful code, with a small car still driving past the window behind it.")

# ---------------------------------------------------------------- ИТОГОВЫЙ ЧЕК 375–401
S(375, 376, "office", "The raccoon tearing off the full long receipt from the register.")
S(377, 378, "office", "The long receipt laid on a big table, the customer in the grey coat and the raccoon leaning over it.")
S(379, 379, "burger", "The burger cook holding a small bill.", "$2.50")
S(380, 380, "burger", "The burger cook handing part of the burger price over the counter to the raccoon.")
S(381, 381, "office", "The raccoon collecting three fee slips in his paw.")
S(382, 382, "office", "The raccoon paying a line of people: a card company clerk, an insurance clerk, a support worker, and a TV screen with a football game.")
S(383, 383, "office", "One small coin left on the raccoon's desk, seen close.", "29¢")
S(384, 384, "gas", "The driver in the red hoodie putting his pay and tips in his wallet at the gas pump.")
S(385, 385, "kitchen", "The burger cook paying rent, staff and food, left with one coin.")
S(386, 386, "cityhall", "The tax clerk's jar getting a coin.")
S(387, 387, "office", "The bottom of the long receipt, seen close, the raccoon's pen at the last line.")
S(388, 389, "street", "The customer in the grey coat, the raccoon, the burger cook, the driver in the red hoodie and the tax clerk standing in a row, each holding one coin.")
S(390, 391, "home", "The customer in the grey coat holding the receipt, looking straight at the viewer.")
S(392, 393, "home", "The customer in the grey coat holding a warm burger bag.")
S(394, 395, "home", "The customer in the grey coat inside the warm dry room, the rain pouring outside the window.")
S(396, 396, "home", "Close view of the rainy window from inside, a warm lamp reflecting in the glass.")
S(397, 397, "street", "A single delivery bag on a map of the town, a long dotted line from the restaurant two miles to the house.")
S(398, 398, "office", "A long table with everything one delivery needs laid out in a row: a driver, a car key, a gas can, an insurance paper, a phone, a card reader, a support headset and a refund envelope.")
S(399, 400, "home", "The customer in the grey coat calmly paying on the phone.")
S(401, 401, "phone", "The raccoon unrolling the price on the phone one line at a time with a sly grin.")

# ---------------------------------------------------------------- СОВЕТЫ И ФИНАЛ 402–424
S(402, 402, "home", "The customer in the grey coat taking notes in a notebook.")
S(403, 403, "burger", "The customer in the grey coat walking into the burger place with an umbrella to pick up his bag.")
C(404, 404, "самовывоз: ~6% комиссии, без сборов за доставку")
S(405, 405, "phone", "A laptop on the kitchen table showing a simple restaurant ordering website with a burger picture.")
S(406, 406, "burger", "The burger cook smiling, keeping the whole payment in his register.")
S(407, 407, "home", "The customer in the grey coat with a calculator and a calendar.")
S(408, 408, "home", "A calendar with two circles on it and the golden membership card, a green check mark.")
S(409, 410, "home", "A calendar with one lonely circle, the golden membership card with coins leaking into a donation box.")
S(411, 411, "phone", "The customer in the grey coat tipping the driver in the red hoodie right in the app, a heart on the screen.")
S(412, 412, "doorstep", "The driver in the red hoodie at the door smiling, holding the bag out to the customer in the grey coat.")
S(413, 413, "burger", "The customer in the grey coat looking up at the chalkboard menu by the register.")
S(414, 415, "burger", "The customer in the grey coat holding his phone up next to the chalkboard, comparing.")
S(416, 417, "home", "The customer in the grey coat on the sofa under a blanket, rain on the window, pressing order with a smile.")
S(418, 418, "doorstep", "The burger bag arriving at the door with its long receipt, the customer in the grey coat reading it calmly.")
S(419, 419, "street", "The raccoon, the burger cook and the driver in the red hoodie waving goodbye in the rain.")
S(420, 420, "office", "A big machine full of gears, cars, phones and kitchens, the raccoon feeding a receipt into it one line at a time.")
S(421, 421, "office", "The raccoon closing the long receipt into a folder, with a sly wink to the viewer.")
S(422, 424, "home", "The customer in the grey coat holding up his own old long receipt to the viewer, curious.")


if __name__ == "__main__":
    ids = len(SHOTS)
    charts = sum(1 for s in SHOTS if s["mode"] == "chart")
    print("кадров:", ids, "| Flow:", ids - charts, "| схем:", charts)
